export default function TermsPage() {
  return (
    <div className="prose prose-invert max-w-3xl">
      <h1>Terms of Service</h1>
      <p>
        FaceRate is intended for entertainment purposes. Results are generated by
        AI and do not constitute medical or professional advice.
      </p>
    </div>
  );
}
